# GitHub Sponsor Configuration
# These links will appear next to the "Sponsor" button on the GitHub repository homepage.

github: tukuaiai # Your GitHub username, e.g.: [octocat]
# patreon: your-patreon-username # Your Patreon username
# open_collective: your-opencollective-project-name # Your Open Collective project name
# ko_fi: your-ko-fi-username # Your Ko-fi username
# tidelift: # Tidelift support
#   - package-name/platform
#   - another-package/platform
# community_bridge: your-community-bridge-project-name # Your Community Bridge project name
# liberapay: your-liberapay-username # Your Liberapay username
# issuehunt: your-issuehunt-username # Your IssueHunt username
# otechie: your-otechie-username # Your Otechie username
custom:
  - 'https://t.me/desci0'
  - 'tron: TQtBXCSTwLFHjBqTS4rNUp7ufiGx51BRey'
  - 'sol: HjYhozVf9AQmfv7yv79xSNs6uaEU5oUk2USasYQfUYau'
  - 'eth: 0xa396923a71ee7D9480b346a17dDeEb2c0C287BBC'
  - 'bsc: 0xa396923a71ee7D9480b346a17dDeEb2c0C287BBC'
  - 'btc: bc1plslluj3zq3snpnnczplu7ywf37h89dyudqua04pz4txwh8z5z5vsre7nlm'
  - 'sui: 0xb720c98a48c77f2d49d375932b2867e793029e6337f1562522640e4f84203d2e'
  - 'telegram: desci0'
  - 'x(twitter): https://x.com/123olp'
